version: '2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./storage/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/patterns:/usr/share/logstash/patterns:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logs:
    image: busybox
    volumes:
      - /home/romain/Documents/Projets/OPPBTP/developpement/#6789/log_apache/files/:/var/log/apache2/

  # filebeat:
  #   build:
  #     context: filebeat/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   command: filebeat -e -strict.perms=false
  #   user: root
  #   volumes:
  #     - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - ./logstash/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
  #   volumes_from:
  #     - logs
  #   networks:
  #     - elk
  #   depends_on:
  #     - logstash

networks:
  elk:
    driver: bridge