# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html
output:
  logstash:
    enabled: true
    hosts:
      - logstash:5044
    timeout: 30
    ssl.certificate_authorities: ["/etc/pki/tls/certs/logstash-beats.crt"]

  # elasticsearch:
  #   # Boolean flag to enable or disable the output module.
  #   enabled: true
  #   hosts: ["elasticsearch:9200"]

filebeat.prospectors:
- type: log
  enabled: true
  document_type: symfony
  paths:
    - /var/log/jarvis/*.log